### ISSUE TITLE
I have a question, please help me?

### ISSUE THREAD

**Issue by muzishen** [GigaVision/PANDA-Toolkit#2]
Hello, I am a rookie at DOTA. 
I understand that the big picture is changed into many patch pictures to detecte via sliding window, and then the results are combined, right?
There is a place I don’t understand, you can give an example.
https://github.com/GigaVision/PANDA-Toolkit/blob/7bc91154aff724d557eeab5a0569e8d213053ada/ImgSplit.py#L71,  param imgrequest and param imgfilters in test, l should how to do?

**Comment by DarkstartsUp** [comment]
param **imgrequest** is a list of images names you want to request, eg. ['1-HIT_canteen/IMG_1_4.jpg', ...]
param **imgfilters** is essential keywords in image name, eg. ['HIT', 'OCT', ...]
You may follow the usage of this function is in demo.py:
https://github.com/GigaVision/PANDA-Toolkit/blob/71231cc058bc04f2ca053aca37032ada9c274990/demo.py#L34

**Comment by muzishen** [comment]
Thank you!

**Comment by muzishen** [comment]
Does the image split script of task 2 (MOT) also use this? 
It seems that there is not key of 'person' in the seqinfo.json file.

**Comment by DarkstartsUp** [comment]
For now ,image split script is only for task 1 (Object Detection on PANDA-IMAGE). However, a few  changes to the data interface can make the code run on PANDA-VIDEO. We will add this part of function in the future, please modify it according to your needs at present.
