### ISSUE TITLE
Confuse about the frame rate in your dataset

### ISSUE THREAD

**Issue by EternalEvan** [GigaVision/PANDA-Toolkit#4]
Thanks for your meaningful work and code!
I have a question about the frame rate in your dataset.
In the appendix of the paper,you show that the frame rate of the Panda-Video is 30 or 12 fps.Is your baseline result of MOT also obtained in that frame rate?
Since you only provide the 2 fps version of Panda-Video,How can I download the 30 or 12 fps version and test on it?
I would appreciate your feedback.

**Comment by DarkstartsUp** [comment]
1. Yes, our baseline result of MOT also obtained in 30/12 frame rate.
2. The data volume is too large for 30 or 12 fps version (800GB in total), so it's very inconvenient to upload and download. If your research needs high frame rate video data, please leave a message. We can provide the data of one scene as a test first.
